sudo: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - oracle-java8-installer
      - pkg-config 
      - zip 
      - clang
      - gcc-4.8
      - g++-4.8
      - zlib1g-dev 
      - unzip 
      - php5-dev 
      - python-numpy 
      - swig 
      - python-dev

language: cpp

cache: ccache

compiler:
  - gcc-4.8

env:
  global:
  - PATH=$HOME/output/bazel/:$PATH 
  - TF_NEED_CUDA=0 
  - VER_BAZEL=0.1.1
  - CC=gcc-4.8
  - CXX=g++-4.8

matrix:
  fast_finish: true
  os: linux 

before_install:
- wget https://github.com/bazelbuild/bazel/releases/download/${VER_BAZEL}/bazel-${VER_BAZEL}-jdk7-installer-linux-x86_64.sh
- sudo chmod +x bazel-${VER_BAZEL}-jdk7-installer-linux-x86_64.sh
- ./bazel-${VER_BAZEL}-jdk7-installer-linux-x86_64.sh --user
- wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.0-28_amd64.deb
- sudo dpkg -i cuda-repo-ubuntu1404_7.0-28_amd64.deb
- git submodule update --init --recursive
- mkdir lib/tensorflow/tensorflow/libtensorflow
- cp ${TRAVIS_BUILD_DIR}/BUILD  lib/tensorflow/tensorflow/libtensorflow/BUILD


install:
- echo $CC
- echo $CXX
- cd lib/tensorflow/tensorflow/libtensorflow
- bazel build --verbose_failures :libtensorflow.so

notifications:
    on_success: never
    on_failure: never
