sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

env:
  global:
    - PATH=$HOME/output/bazel/:$PATH

before_install:
- sudo add-apt-repository -y ppa:webupd8team/java &> /dev/null
- sudo apt-get update -qq
- sudo apt-get install -y oracle-java8-installer
- sudo apt-get install -y pkg-config zip g++ zlib1g-dev unzip
- git clone https://github.com/bazelbuild/bazel.git
- cd bazel
- git checkout tags/0.1.1
- ./compile.sh
- sudo apt-get install -y python-numpy swig python-dev
- cd ..
- wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.0-28_amd64.deb
- sudo dpkg -i cuda-repo-ubuntu1404_7.0-28_amd64.deb --root=/usr/local/cuda
- cd lib/tensorflow
- ./configure
