sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

env:
  global:
    - PATH=$HOME/output/bazel/:$PATH
    - TF_NEED_CUDA=0
    - #CUDA_TOOLKIT_PATH=/usr/local/cuda-7.0
    - #CUDNN_INSTALL_PATH=/usr/local/cuda-6.5

before_install:
- sudo add-apt-repository -y ppa:webupd8team/java &> /dev/null
- sudo apt-get update -qq
- sudo apt-get install -y oracle-java8-installer pkg-config zip g++ zlib1g-dev unzip php5-dev locate
- git clone https://github.com/bazelbuild/bazel.git
- cd bazel
- git checkout tags/0.1.1
- ./compile.sh
- sudo apt-get install -y python-numpy swig python-dev
- cd ..
- wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.0-28_amd64.deb
- sudo dpkg -i cuda-repo-ubuntu1404_7.0-28_amd64.deb
- sudo updatedb
- locate cuda
- #wget https://s3-eu-west-1.amazonaws.com/christopherbourez/public/cudnn-6.5-linux-x64-v2.tgz
- #tar xf cudnn-6.5-linux-x64-v2.tgz
- #rm cudnn-6.5-linux-x64-v2.tgz
- #sudo cp cudnn-6.5-linux-x64-v2/cudnn.h /usr/local/cuda-7.5/include/
- #sudo cp cudnn-6.5-linux-x64-v2/libcudnn* /usr/local/cuda-7.5/lib64/
- git submodule init
- git submodule update
- cp ${TRAVIS_BUILD_DIR}/BUILD  lib/tensorflow/tensorflow/BUILD
- cd lib/tensorflow
- ./configure
- bazel build -c opt //tensorflow:all

notifications:
    on_success: never
    on_failure: never

os:
  - linux

matrix:
  fast_finish: true
